version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: cortexweaver-neo4j
    environment:
      NEO4J_AUTH: neo4j/cortexweaver
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

  mcp-neo4j-memory:
    image: mcp/memory:latest
    container_name: cortexweaver-mcp-neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: cortexweaver
    depends_on:
      - neo4j
    restart: unless-stopped
    ports:
      - "3001:3001"

  github-mcp-server:
    image: mcp/github:latest
    container_name: cortexweaver-github-mcp
    environment:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_TOKEN}
      GITHUB_TOOLSETS: "context,repos,issues,pull_requests,actions,code_security"
      GITHUB_READ_ONLY: "1"
      GITHUB_DYNAMIC_TOOLSETS: "1"
    restart: unless-stopped
    ports:
      - "3002:3002"

volumes:
  neo4j_data:
  neo4j_logs:
